### ISSUE TITLE
Cannot access handlebars partials

### ISSUE THREAD

**Issue by danevans** [brunch/handlebars-brunch#10]
This issue may belong in either the main brunch project or the brunch-with-chaplin project but for now I thought it was most appropriate here. I also looked around and couldn't find an answer to this anywhere else.

I expect to be able to create a file in the templates directory called `_something.hbs` that says:

```
<li>line item</li>
```

and then in another view do:

```
<ul>
{{> something}}
</ul>
```

and get the output:

``` html
<ul>
<li>line item</li>
</ul>
```

It appears that this is just not possible because partials are ignored and certainly not registered via the Handlebars.registerPartial method.

If this just isn't supported is there a recommended workaround?

**Comment by reubano** [comment]
Updated for brunch 1.8

```coffee-script
register 'partial', (name, context, options) ->
  unless Handlebars.partials[name]
    template = require "views/templates/partials/#{name}"
    string = new Handlebars.SafeString template
    Handlebars.registerPartial(name, string)

  new_context = _.extend options?.hash ? {}, context
  template = Handlebars.partials[name].string 
  new Handlebars.SafeString template new_context
```
```
{{partial 'mypartial' this parameter=value}}
```

**Comment by devel-pa** [comment]
Old issue, still opened. 
'''
Handlebars.registerPartial("partialName",  require('../templates/PartialTemplate'));
'''

**Comment by Tolgor** [comment]
I've made a workaround to use precompiled templates as partials at runtime:

Register a new "partial" helper:
```
Handlebars.registerHelper('partial', (options) => {
  return require(`templates/${options.hash.name}.hbs`);
});
```

And use it like this in a template:
`{{> (partial name='archive')}}`

This will include "templates/archive.hbs".
