### ISSUE TITLE
Compatibility with Handlebars 2.0

### ISSUE THREAD

**Issue by pierr** [brunch/handlebars-brunch#32]

**Comment by wolfd** [comment]
I think the only blocker on this not being ready is if people have handlebars 1.3.0 syntax that isn't compatible with 2.0.0. This shouldn't really be a problem if they have their package.json files setup correctly.
 
I would argue that you should tag a new release, and bump the version of handlebars-brunch to 2.0.0 to indicate a possible breaking change.

Thoughts?

**Comment by es128** [comment]
yes, fair enough, I'll try to do this today

**Comment by es128** [comment]
e4689567ee7694a27e98b5b18d33997268f8c1c1
