### ISSUE TITLE
Different compilation on vendor than in app

### ISSUE THREAD

**Issue by devel-pa** [brunch/handlebars-brunch#33]
There is any way to achieve the default compilation in app and namespaced in vendor?
Thanks,
Paul

**Comment by es128** [comment]
Perhaps by using brunch's env/overrides settings and compiling in separate steps (or running two separate brunch instances simultaneously)

**Comment by es128** [comment]
Also, a sufficiently creative `pathReplace` regex may be able to do the trick all in one shot. 

If not, perhaps we need to allow passing a function for that setting to allow more complex operations.
