### ISSUE TITLE
Template variables fail to render

### ISSUE THREAD

**Issue by reduxdj** [brunch/handlebars-brunch#38]
I have a view with one variable in the model, when i try to render the view with the template, the context is always 0. This happens in a few of my projects.

Problem observed in Handlebars 1.0 with Handlebars-brunch 1.7.1
Problem observed in Handlebars 2.0 with Handlebars-brunch 1.9.1

package.json

{
  "author": "Patrick Lemiuex",
  "name": "backbone_bootstrap",
  "description": "Agent Bidder Tool",
  "version": "0.0.1",
  "homepage": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "test": "cake build:test",
    "start": "./node_modules/.bin/brunch watch --server",
    "build": "./node_modules/.bin/brunch build --production"
  },
  "dependencies": {
    "brunch": "^1.7.17",
    "bower": "~1.3.12",
    "clean-css-brunch": ">= 1.0 < 1.8",
    "moment": "2.9.0",
    "mongoose": "3.8.24",
    "coffee-script": "~1.9.1",
    "coffee-script-brunch": ">= 1.0 < 1.8",
    "coffeelint-brunch": "^1.7.0",
    "css-brunch": ">= 1.0 < 1.8",
    "handlebars-brunch": "1.9.1",
    "highlight": ">=0.2.3",
    "javascript-brunch": ">= 1.0 < 1.8",
    "stylus-brunch": ">= 1.0 < 1.8",
    "uglify-js-brunch": ">= 1.0 < 1.8"
  },
  "devDependencies": {
    "chai": "^1.9.1",
    "coffeelint": "^1.6.0",
    "jsdom": "^1.0.0",
    "mocha": "^1.21.4",
    "zombie": "^2.0.4"
  }
}

config.coffee

exports.config =
  paths:
    'public': 'public'
  assets: [
    'images'
    'assets'
    'fonts'
  ]
  vendor: [
    'fonts'
  ]
  coffeelint:
    pattern: /^app\/.*\.coffee$/
    options:
      indentation:
        value: 2
        level: "error"
      max_line_length:
        value: 80
        level: "ignore"
  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js':  /^(bower_components|vendor)/
        'test/js/test.js': /^test(\/|\\)(?!vendor)/
        'test/js/test-vendor.js': /^test(\/|\\)(?=vendor)/
        order:
          # Files in `vendor` directories are compiled before other files
          # even if they aren't specified in order.
          before: [

          ]
    stylesheets:
      defaultExtension: 'styl'
      joinTo: 'css/app.css'
      order:
        before: [
          'app/css/*'
        ]
        after: [

        ]
    templates:
      defaultExtension: 'hbs'
      joinTo: 'javascripts/app.js'
  # Settings of web server that will run with `brunch watch [--server]`.
  plugins:
    coffeelint:
      pattern: /^app\/.*\.coffee$/
      options: require('./coffeelint.json')

Render functions:

  Get the model data to render the view.
  @return Object - property object that view will be rendered from
  ###
  getRenderData: ->
    o = { host: App.host }
    _.extend({}, o, @model?.toJSON() )

  ###
  Get the model data to render the view.
  @return Object - property object that view will be rendered from
  ###
  render: ->
    @trigger "#{@cid}:render:before", this
    @beforeRender()
    @$el.attr('data-cid', @cid)
    if @model
      @$el.attr('data-model-cid', @model?.cid)
      @$el.attr('data-model-id', @model?.id)
    @html( @template( @getRenderData() ) )
    @rendered = yes
    @trigger "#{@cid}:render:after", this
    @afterRender()
    this

**Comment by paulmillr** [comment]
Please use backticks to format code: `
