### ISSUE TITLE
npm3 issue: handlebars.runtime.js not found

### ISSUE THREAD

**Issue by toabi** [brunch/handlebars-brunch#40]
npm3 doesn't nest dependencies anymore. This leads to

`… [Error: ENOENT, open 'node_modules/handlebars-brunch/node_modules/handlebars/dist/handlebars.runtime.js'] … `

**Comment by es128** [comment]
https://github.com/brunch/handlebars-brunch/blob/master/index.js#L32

I guess we'll need to `require.resolve('handlebars')` or something like that to derive the correct path.

PR welcome of course.

**Comment by devel-pa** [comment]
Hi,
I'm working on a PR but I have an issue with include order, as `ns` is included before runtime. Any advice?
Thanks

**Comment by urosgruber** [comment]
Any news on this?

**Comment by johdirr** [comment]
+1

**Comment by KATT** [comment]
I did a temp workaround in my build script that does `cd node_modules/handlebars-brunch && npm install` after `npm install`

**Comment by devel-pa** [comment]
The fix looks simple, but the unexpected array sorting stays in the way.

**Comment by paulmillr** [comment]
try 2.0.0 folks
