### ISSUE TITLE
Error with postinstall.js symlinking to handlebars on install

### ISSUE THREAD

**Issue by MaffooBristol** [brunch/handlebars-brunch#45]
##### Node v5.1.1, npm v3.3.12, latest handlebars-brunch, Centos 7

Not sure if this is related to https://github.com/brunch/handlebars-brunch/issues/40 ?

Doesn't seem to work even if I `npm install handlebars` first. Also seems to be entirely independent of node and npm version. (and even handlebars-brunch version, actually)

```
> handlebars-brunch@1.10.1 postinstall /var/www/html/plain-bear/client/node_modules/handlebars-brunch
> node ./postinstall.js

fs.js:945
  return binding.symlink(preprocessSymlinkDestination(destination, type, path),
                 ^

Error: ENOENT: no such file or directory, symlink '/var/www/html/plain-bear/client/node_modules/handlebars/dist/handlebars.js' -> '/var/www/html/plain-bear/client/node_modules/handlebars-brunch/dist/handlebars.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at /var/www/html/plain-bear/client/node_modules/handlebars-brunch/postinstall.js:17:10
    at Array.forEach (native)
    at /var/www/html/plain-bear/client/node_modules/handlebars-brunch/postinstall.js:14:9
    at Array.forEach (native)
    at /var/www/html/plain-bear/client/node_modules/handlebars-brunch/postinstall.js:13:7
    at Array.forEach (native)
    at Object.<anonymous> (/var/www/html/plain-bear/client/node_modules/handlebars-brunch/postinstall.js:12:9)
    at Module._compile (module.js:425:26)
```

Sometimes I also get this error, which happened when I tried it with a clean copy of my codebase:
```
Cannot find module '/root/plain-bear/client/node_modules/handlebars-brunch/postinstall.js'
```

I've got a circle-ci build that works fine, and it's fine on my local machine. Just *something* has broken on the server since trying to upgrade handlebars-brunch and I have no idea what it could be!

**Comment by es128** [comment]
cc @devel-pa

**Comment by devel-pa** [comment]
Hi,

Never tested with CentOS. Here Windows Only. Also not tested with Node 5.

I have some other types of issues because of that and I think the solution of symlinking looks great but not bulet proof, mostly because the user that install the scripts has no symlink creation rights.

I think a different solution have to be found, maybe file copying.

Otherwise for the moment I have no idea. 

Paul

PS: The only idea, maybe wrong, for the second issue is that `npm install` has not enough privileges. Also, can you check if `postinstall.js` exists in that folder?

**Comment by MaffooBristol** [comment]
Hey,

I've tried it as sudo, as root, with everything chmodded to 777- I can't see any other things that could be related to permissions!

It's almost as if, when trying to create the symbolic link, it hasn't yet installed its own handlebars dependency.

I even cloned this repo and npm installed inside it on my centos box and it came up with the same issue.

The fact it works on other machines shows that the server is in some way configured strangely, but it's only failing on this one module and as far as I know, I haven't modified on the server other than updating my package.json to include newer deps (this included) and trying to reinstall the modules. I even completely wiped my system of node and reinstalled it from scratch!

Thanks,
Matt

**Comment by devel-pa** [comment]
Then, I'm afraid that even if we are copying the files instead of linking will be an issue.

**Comment by devel-pa** [comment]
The only solution I'm seeing for the moment is to inject `ns.js` before first compiled template.

**Comment by es128** [comment]
@MaffooBristol do the files exist in the correct location *after* the `npm install` failed?

Have you tried with other versions of node on that CentOS, box, like 4.x LTS?

**Comment by MaffooBristol** [comment]
Hi @es128 - No, the handlebars-brunch folder is never created. Alphabetically, things that occur after it after exist, but the directory is never generated.

I've tried with all other versions of node and npm and the issue is still the same.

**Comment by es128** [comment]
Well, it must have been generated, but I suppose npm deletes it after the failure.

Perhaps it's a race condition being aggravated by an extremely slow file system.

**Comment by MaffooBristol** [comment]
That would make sense re the failure deletion.

Not sure about the slow fs thing though. Standard 1gb digital ocean box,
I've even shut down all other services to make sure something's not just
caning the RAM.

**Comment by es128** [comment]
Somehow in this particular environment, it appears that files that should have just recently been written are causing errors to be thrown when node attempts to operate on them. You've shown two completely separate errors that both appear to have that sort of cause.

I'm not saying it totally makes sense - I'm kind of scratching my head about it - but that's what it looks like from what you're showing.

I wonder if modifying the postinstall script to something like `sleep 5 && node ./postinstall.js` would have an impact.

**Comment by es128** [comment]
Not that I'm proposing that as a real solution, but as an experiment to be attempted in this problematic environment.

**Comment by MaffooBristol** [comment]
Thanks. I tried `sleep 5 && node ./postinstall.js` and it made no difference :confounded:

**Comment by es128** [comment]
How? Did you clone the repo locally and install from the relative path?

**Comment by MaffooBristol** [comment]
Yep.

**Comment by MaffooBristol** [comment]
It did the five second pause, so it definitely worked as expected for the "experiment"

**Comment by es128** [comment]
:confounded: is right

So how about now you change it to `sleep 50` and look around at what ended up on disk while you're waiting for it to blow up.

**Comment by MaffooBristol** [comment]
Okay, watching it while it's sleeping (seasonal? creepy?) and it has generated a `node_modules/handlebars-brunch` folder, but no subdirectories (eg, its own node_modules) inside:

```
[root@PlainBear client]# tree node_modules/handlebars-brunch/
node_modules/handlebars-brunch/
├── CHANGELOG.md
├── index.js
├── ns.js
├── package.json
├── postinstall.js
└── README.md

0 directories, 6 files
```

It has *definitely* created the `node_modules/handlebars` directory, however.

**Comment by es128** [comment]
Well, right, this is with npm 3 flattened deps, which is why we use `require.resolve` now. Please confirm that `/var/www/html/plain-bear/client/node_modules/handlebars/dist/handlebars.js` is present. If it is, then the ENOENT on that path doesn't make sense.

**Comment by MaffooBristol** [comment]
That file exists, yes, and is 777 too. Getting weirder and weirder.

**Comment by MaffooBristol** [comment]
Another little note to add to this- it only seems to be having issues with handlebars-brunch versions >=1.10.0 and <= 1.4.0 ... all other versions seemingly work.

**Comment by denar90** [comment]
Have same issue with postinstall.js symlinking in travis.

**Comment by ssalinas** [comment]
Seeing the same issue on travis as well, has anyone found a workaround/solution for this yet?

**Comment by denar90** [comment]
I'm using `1.9.0` and my build passing.

**Comment by devel-pa** [comment]
I've changed the symlink to copy.
Status: works on my computer
If you want to test https://github.com/devel-pa/handlebars-brunch pls give a feedback to propose a PR.

**Comment by Florian-R** [comment]
@devel-pa I was running on this one intermittently (on a slow machine indeed) and for now I haven't seen failures since I use your fork, so I'd say go ahead and PR this.

**Comment by devel-pa** [comment]
PR submitted.

**Comment by devel-pa** [comment]
@es128 looks like copying files it's a better solution than symlinks. What do you think?

**Comment by paulmillr** [comment]
try 2.0.0 folks

**Comment by MaffooBristol** [comment]
Cheers for that guys. Seems it also worked only once I'd upgraded brunch from 2.0.2 to 2.2.2 - is that to be expected? Otherwise brunch build would just hang without error

**Comment by paulmillr** [comment]
yes
