### ISSUE TITLE
Cannot set property 'Handlebars' of undefined

### ISSUE THREAD

**Issue by micahwedemeyer** [brunch/handlebars-brunch#51]
I'm probably doing something stupid, but I just thought I'd ask.

brunch: 2.1.3 (also tried with 2.3.2, same error)
handlebars: 4.0.5
handlebars-brunch: 2.0.1

This is running as part of a Phoenix Framework application build process.

(I also tried downgrading brunch to 2.0.0, but that caused another error to where it wouldn't even start up. That could be a phoenix thing.)

I get no errors from brunch, but when I load up `vendor.js` in the browser I get this error: Cannot set property 'Handlebars' of undefined

It looks related to this block of code in handlebars.runtime

```
(function webpackUniversalModuleDefinition(root, factory) {
if(typeof exports === 'object' && typeof module === 'object')
    module.exports = factory();
else if(typeof define === 'function' && define.amd)
    define([], factory);
else if(typeof exports === 'object')
    exports["Handlebars"] = factory();
else
    root["Handlebars"] = factory();
```

It falls through to the final else and that's where the error occurs.

I haven't changed any default settings in the handlebars-brunch config.

Any ideas?

**Comment by paulmillr** [comment]
@goshakkk

**Comment by goshakkk** [comment]
@micahwedemeyer hey, can you create a repo with a small app that demo's the issue? Thanks

**Comment by micahwedemeyer** [comment]
Yes, I created a [brand new phoenix app](https://github.com/micahwedemeyer/brunch-handlebars-issue) with nothing except the brunch-handlebars plugin and it has the same issue. If you were asking for a bare brunch app (ie. no Phoenix), I'm afraid I've never done that.

**Comment by goshakkk** [comment]
I've found the issue to be Babel, which, apparently, processes vendor files as well, turning these lines of `handlebars`:

```javascript
(function webpackUniversalModuleDefinition(root, factory) {
    if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object' && (typeof module === 'undefined' ? 'undefined' : _typeof(module)) === 'object') module.exports = factory();
    else if (typeof define === 'function' && define.amd) 
        define([], factory);
    else if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') 
        exports["Handlebars"] = factory();
    else 
        root["Handlebars"] = factory();
})(this, function () {
```

into

```javascript
(function webpackUniversalModuleDefinition(root, factory) {
    if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object' && (typeof module === 'undefined' ? 'undefined' : _typeof(module)) === 'object') module.exports = factory();
    else if (typeof define === 'function' && define.amd) 
        define([], factory);
    else if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') 
        exports["Handlebars"] = factory();
    else 
        root["Handlebars"] = factory();
})(undefined, function () {
```

— resulting in `root` being `undefined` instead of `window`

@paulmillr do you think we should extend `babel-brunch` default ignore from `/^(bower_components|vendor)/` to `/^(bower_components|node_modules|vendor)/` to address the cases when brunch plugins can include their own vendor JS.

It will also prevent anything in node_modules from being processed by babel: on one hand, the npm modules that target the browser usually come in ES5, on another... it could sometimes be needed?

What it boils down to, then, is changing `babel-brunch` default ignore to include either `node_modules` or specifically `node_modules/*-brunch` only. What do you think @paulmillr?

**Comment by paulmillr** [comment]
let's ignore at least node_modules/*brunch for now

**Comment by goshakkk** [comment]
Submitted a PR https://github.com/babel/babel-brunch/pull/24 cc @paulmillr

**Comment by thiagogabriel** [comment]
@micahwedemeyer did it solve for you? I'm having the same problem with the last version.

**Comment by goshakkk** [comment]
@thiagogabriel what's your package.json like?

**Comment by goshakkk** [comment]
@thiagogabriel if you are using babel-brunch and override `ignore`, make sure it includes `node_modules`... If you don't override, https://github.com/babel/babel-brunch/pull/28 should provide a slightly better default

If you don't use babel-brunch at all but are experiencing the described issue, a minimal app reproducing the issue would be of much help.

Thanks!

**Comment by thiagogabriel** [comment]
Hi @goshakkk, thanks for your help.
The `package.json` is:
```json
{
  "repository": {},
  "dependencies": {
    "babel-brunch": "^6.0.2",
    "brunch": "~2.1.3",
    "clean-css-brunch": "~1.8.0",
    "css-brunch": "~1.7.0",
    "handlebars-brunch": "^2.0.1",
    "javascript-brunch": "~1.8.0",
    "phoenix": "file:deps/phoenix",
    "phoenix_html": "file:deps/phoenix_html",
    "uglify-js-brunch": "~1.7.0"
  }
}
```
The demo app is here https://github.com/thiagogabriel/phoenix_handlebars_brunch

**Comment by goshakkk** [comment]
@thiagogabriel the config does override babel's ignore. Can you see if changing

```javascript
ignore: [/web\/static\/vendor/]
```

to

```javascript
ignore: [/web\/static\/vendor/, /node_modules/]
```

Fixes it for you?

**Comment by thiagogabriel** [comment]
@goshakkk it fixed but I still can't use the `Handlebars.compile` for example. Do you have any idea what can I do in order to make it work?
The error is `Uncaught TypeError: Handlebars.compile is not a function`.
The demo app was updated https://github.com/thiagogabriel/phoenix_handlebars_brunch

Thanks!

**Comment by goshakkk** [comment]
@thiagogabriel by default, `handlebars-brunch` only includes the handlebars runtime (which is enough to render templates that were pre-compiled by brunch). If you want to compile templates right in the browser, set `config.plugins.handlebars.include.runtime` to `false` (see `handlebars-brunch`'s README section on config options https://github.com/brunch/handlebars-brunch#options)

**Comment by florinpatrascu** [comment]
fwiw, and in case you fixed it already, I encountered the same problem, and fixed it by simply following @goshakkk's advice. Here's what I have in my `brunch-config.js` config file (excerpt):

```js
  // Configure your plugins
  plugins: {
    babel: {
      // Do not use ES6 compiler in vendor code
      ignore: [/web\/static\/vendor/, /node_modules/]
    },
    handlebars:{
      include: {
        runtime: false
      }
    }
  }, ...
```

**Comment by adam1920** [comment]
Solved for me:
set in `.babelrc` file:

```
{
        "presets": ["es2015"],
        "compact": false,
        "ignore": ["/bower_components/handlebars/"]
}

```
