### ISSUE TITLE
Not sure how to use this

### ISSUE THREAD

**Issue by ballPointPenguin** [brunch/handlebars-brunch#52]
Hello.
I am not new to Javascript, Node or Handlebars, but I am new to Brunch.
Maybe it is obvious to brunchies what to do here, but I am lost.

- Do I need to include `<script ... type="text/x-handlebars-template">` in my markup?
- Do I have to define the values of my handlebars variables in my application.js (in the app. namespace) ?
- Is the default to put all the templates in the top-level of app/templates ?

I've tried a few things, but nothing has rendered and I haven't gotten any errors either. A small example would be very helpful.

**Comment by paulmillr** [comment]
1. Put your stuff inside `app/templates/user.hbs` (for example)
2. Load the template with this code: `var tpl = require('templates/user')`
3. Calling `tpl({prop: 'value'})` would render the template and return a string. You can now append the string to DOM manually or using a framework of your choice.

Some clarifications:

1. No `<script>` magic is needed.
2. You can put templates inside any structure you'd like. For example `app/components/user/tpl.hbs` would work too.

**Comment by ballPointPenguin** [comment]
Thank You!
