### ISSUE TITLE
AMD option does not affect template compilation output

### ISSUE THREAD

**Issue by ccedgordon** [brunch/handlebars-brunch#53]
Just wanted to confirm, before I go too far finding an alternative, that specifying the amd option in this plugin only affects the included Handlebars vendor file and does not change the compiled template code. I am still seeing it as expecting a global Handlebars object with a .template function. I think what I am looking for is for the output to loadable as a requirejs compatible module. Right now, i get a message that Handlebars is not defined if I load HB in a way that is compatible with require. I have used this plugin for years and any help you can offer would be appreciated.

**Comment by paulmillr** [comment]
yeah AMD is not really supported
