### ISSUE TITLE
static compilation example not working

### ISSUE THREAD

**Issue by jffng** [brunch/handlebars-brunch#62]
Hi there

I can't get the static compilation to work. My config:

```
exports.config = {
	plugins: {
        	on: ['handlebars-brunch', 'handlebars'],
        	handlebars: {
            		locals: {
				title: 'Brunch is awesome!'
			},
        	}
    	},
	npm: {globals: {
		$: 'jquery'
	}},
	files: {
		javascripts: {
			joinTo: {
				'libraries.js': /^(?!app\/)/,
				'app.js': /^app\//
			}
		},
		stylesheets: {
			joinTo: {
				'app.css': 'app/styles/main.less'
			}
		}
	}
}
```

`brunch build` results in a copy of `your_name.hbs` in `public`. Running brunch 2.9.1 and handlebars-brunch 2.0.1.

**Comment by shvaikalesh** [comment]
Hello, @jffng. `handlebars-brunch` with static templates support was not yet published on npm. Please, install from `master` for now.
