### ISSUE TITLE
2.10.0 causes handlebar not to load in our project

### ISSUE THREAD

**Issue by nulian** [brunch/handlebars-brunch#63]
With 2.10.0 I get an error in the following block in the handlebars.runtime.js. That root is undefined.

`
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["Handlebars"] = factory();
	else
		root["Handlebars"] = factory();
})(this, function() {
`

Our project has no problems compiling at version 2.0.1

I load handlebars with window.Handlebars = require('handlebars/runtime');
Mostly because we also have some old code that isn't compatible with require yet.

**Comment by shvaikalesh** [comment]
Do you use `babel-brunch`?

**Comment by nulian** [comment]
It is loaded but babel is limited to parse only certain folders.
