### ISSUE TITLE
handlebars is compiling in the bom from templates

### ISSUE THREAD

**Issue by mr-miles** [brunch/handlebars-brunch#65]
Hi,

I've been using brunch successfully for a while and just started trying to precompile handlebars templates so I can bundle them all up.  It's working well except...

file.data when passed in contains a bom (yes, i'm on windows).  handlebars is dilligently encoding it and including it in the compiled template.  is this something you've come across?  i'm not sure whether this is an issue with the brunch layer or specific to the handlebars part, i haven't come across the problem elsewhere where i am compiling typescript...

it seems the fix is pretty trivial - but what's the best place to apply it?
body = body.replace(/^\uFEFF/, '');

thanks for your help,

miles

**Comment by shvaikalesh** [comment]
Hey @mr-miles. Thanks for the report, we will include BOM stripping in `3.0` release of Brunch. Progress in https://github.com/brunch/brunch/pull/1664

**Comment by mr-miles** [comment]
Thanks!

Is there a way I can use the existing plugins to achieve the bom stripping (or just do a find-and-replace in the final concatenated output files)?  I'd like to avoid needing my own plugin if at all possible.

At the moment, the boms are causing non-optimized builds to have "illegal character errors" in the browser (it seems an optimized build does enough replacement to get round this, with the bom being rendered as text the final issue)

Miles
